server:
  port: 8080

spring:
  application:
    name: libronet-api-gateway
  cloud:
    gateway:
      routes:
        # 1. Ruta hacia el nuevo Servicio de Catálogo (Búsquedas)
        - id: catalogo-service
          uri: lb://libronet-catalogo
          predicates:
            - Path=/api/catalogo/**
            
        # 2. Ruta hacia el Servicio de Préstamos (Transacciones)
        - id: prestamos-service
          uri: lb://libronet-prestamos
          predicates:
            - Path=/api/prestamos/**

        # 3. Ruta hacia el Módulo de Simulación Académica (Dekker)
        - id: simulacion-service
          uri: lb://libronet-prestamos
          predicates:
            - Path=/api/simulacion/**

        # 4. Ruta para el Servicio de Autenticación
        - id: auth-service
          uri: lb://libronet-prestamos
          predicates:
            - Path=/api/auth/**
            
        # 5. Ruta directa a Sede Norte (para simulación)
        - id: prestamos-norte-direct
          uri: http://libronet-prestamos-norte:8081
          predicates:
            - Path=/api/eleccion/norte/**
          filters:
            - RewritePath=/api/eleccion/norte/(?<remaining>.*), /api/eleccion/$$\{remaining}

        # 6. Ruta directa a Sede Sur (para simulación)
        - id: prestamos-sur-direct
          uri: http://libronet-prestamos-sur:8083
          predicates:
            - Path=/api/eleccion/sur/**
          filters:
            - RewritePath=/api/eleccion/sur/(?<remaining>.*), /api/eleccion/$$\{remaining}

        # 7. Ruta para el Servicio de Elección de Líder (balanceado)
        - id: eleccion-service
          uri: lb://libronet-prestamos
          predicates:
            - Path=/api/eleccion/**
            
            
      # Reglas de seguridad para permitir que React se comunique
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true