spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_ALLOWED_ORIGIN:http://localhost:5173}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTPORT:eureka:8761}/eureka/
  instance:
    prefer-ip-address: true
    hostname: gateway
