server:
  port: ${PORT:8084}

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      sede: Sede Este
      nodeId: 3

eleccion:
  node-id: 3
  node-name: Sede Este

reloj:
  drift-ms: 12000
