spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/biblioteca_db}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_BASE_URL:http://${EUREKA_HOSTPORT:eureka:8761}/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ${SERVICE_HOST:prestamos}

reloj:
  drift-ms: 5000
