server:
  port: ${PORT:8083}

eureka:
  instance:
    instance-id: ${spring.application.name}:${SERVICE_HOST:localhost}:${server.port}
    metadata-map:
      sede: Sede Sur
      nodeId: 2

eleccion:
  node-id: 2
  node-name: Sede Sur

reloj:
  drift-ms: -15000
