server:
  port: ${PORT:8082} # Este servicio corre en el puerto 8082

spring:
  application:
    name: libronet-catalogo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/biblioteca_db}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTPORT:localhost:8761}/eureka/
  instance:
    prefer-ip-address: true